pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url = uri("https://maven.aliyun.com/repository/public")
        }
        maven {
            url = uri("https://maven.aliyun.com/repository/gradle-plugin")
        }
        gradlePluginPortal()
    }

    resolutionStrategy {
        eachPlugin {
            def id = it.requested.id.getId()
            System.out.println("use plugin: '${id}'")

            switch (id) {
                case 'org.jetbrains.intellij.platform':
                    useVersion("${intellijGradle}")
                    break
                case 'org.jetbrains.intellij.platform.module':
                    useVersion("${intellijGradle}")
                    break
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenLocal()
        maven {
            url = uri("https://maven.aliyun.com/repository/public")
        }
        maven {
            url = uri("https://maven.aliyun.com/repository/gradle-plugin")
        }
    }
}

include ':app'

rootProject.name = 'mybatis-navigator'
rootProject.buildFileName = "build.gradle.kts"

rootProject.children.forEach(e -> {
    e.buildFileName = "build.gradle.kts"
})
