name: CI - build plugin

on: workflow_dispatch

jobs:
  build:
    env:
      PLUGIN_DIR: build/libs

    runs-on: ubuntu-latest
    container: bellsoft/liberica-openjdk-debian:17

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Show env & workspace
        run: env && echo -e "\n${PWD}\n" && ls -alh
      - name: Show JDK
        run: command -v java && java -version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with gradle
        run: |
          ./gradlew buildPlugin \
            -Dorg.gradle.daemon=false --warning-mode all \
            -Dorg.gradle.jvmargs="-Xmx4096m -XX:+UseZGC -Djava.complier=NONE -Dfile.encoding=UTF-8"
      - name: Show build dir
        run: ls -alh -- "${PLUGIN_DIR}"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{ env.PLUGIN_DIR }}
