name: CI - build plugin

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      PLUGIN_DIR: app/build/distributions
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: clone source
        run: |
          git config --global --add safe.directory "*"

          git init
          git remote add x ${{github.server_url}}/${{ github.repository }}.git
          git fetch --no-tags --prune --no-recurse-submodules --depth=1 x +${{ github.sha }}
          git checkout FETCH_HEAD
      - name: build with gradle
        run: |
          ${JAVA_HOME_21_X64}/bin/java -Xms64m -Xmx64m -Xint -Dfile.encoding=UTF-8 \
            -classpath gradle/wrapper/gradle-wrapper.jar  \
              org.gradle.wrapper.GradleWrapperMain        \
                -Dorg.gradle.appname=gradlew.py -Dorg.gradle.daemon=false --warning-mode all \
                --gradle-distribution-url 'https://services.gradle.org/distributions/gradle-8.13-bin.zip' \
                buildPlugin
      - name: show files as tree
        run: tree -- "${PLUGIN_DIR}"
      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: build-artifact
          path: ${{ env.PLUGIN_DIR }}
