name: CI - build plugin

on: workflow_dispatch

jobs:
    build:
        env:
            JDK_URL: https://download.bell-sw.com/java/16.0.1+9/bellsoft-jdk16.0.1+9-linux-amd64-lite.tar.gz
            JDK_TAR: jdk.tar.gz
            JDK_DIR: jdk

        runs-on: ubuntu-latest

        steps:
            - name: Show workspace
              run: echo "${PWD}" && ls -alh && env

