name: CI - build plugin

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      PLUGIN_DIR: app/build/libs

    runs-on: ubuntu-latest
    container: bellsoft/liberica-openjdk-debian:21

    steps:
      - name: git checkout src
        uses: actions/checkout@v4
      - name: inspect openjdk
        run: command -v java && java -version
      - name: build with gradle
        run: |
          bash gradlew.sh buildPlugin \
            -Dorg.gradle.daemon=false --warning-mode all \
            -Dorg.gradle.jvmargs="-Xmx4096m -XX:+UseZGC -Djava.complier=NONE -Dfile.encoding=UTF-8"
      - name: show build dir
        run: ls -alh -- "${PLUGIN_DIR}"
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ env.PLUGIN_DIR }}
